return {
  -- { "sindrets/diffview.nvim", enabled = false },
  { "hrsh7th/cmp-nvim-lsp-signature-help", enabled = false },
  { "erhickey/sig-window-nvim", enabled = false },
  { "p00f/clangd_extensions.nvim", enabled = false },
  { "ray-x/lsp_signature.nvim", enabled = false },
  -- { "ahmedkhalf/project.nvim", enabled = false },
  -- { "HiPhish/rainbow-delimiters.nvim", enabled = false },
  { "abecodes/tabout.nvim", enabled = false },
  -- { "lilibyte/tabhula.nvim", enabled = false },
  -- { "phaazon/hop.nvim", enabled = false },
  { "Exafunction/codeium.nvim", enabled = false },
  -- { "kylechui/nvim-surround", enabled = false },
  -- { "folke/todo-comments.nvim", enabled = false },
  -- { "ginsburgnm/rich.nvim", enabled = false },
  -- { "gaoDean/autolist.nvim", enabled = false },
  -- { "ray-x/go.nvim", enabled = false },
  -- { "karb94/neoscroll.nvim", enabled = false },
  -- { "folke/flash.nvim", enabled = false },
  -- { "Mr-LLLLL/interestingwords.nvim", enabled = false },
  -- { "lewis6991/gitsigns.nvim", enabled = false },
  -- { "folke/trouble.nvim", enabled = false },
}
